import { z } from "zod";

const agentSchema = z.enum(["claude", "cursor", "codex", "windsurf", "copilot"]);

const targetConfigSchema = z.object({
  output: z.string(),
});

const scanConfigSchema = z.object({
  include: z.array(z.string()),
  exclude: z.array(z.string()),
  maxDepth: z.number().int().positive(),
});

const discoverConfigSchema = z.object({
  paths: z.record(z.unknown()).default({}),
  dedupeGlobal: z.boolean().default(true),
});

const srsConfigSchema = z.object({
  path: z.string(),
  skillPath: z.string(),
  moduleMap: z.record(z.array(z.string())).default({}),
});

export const gateModeSchema = z.enum(["sensitive-only", "strict"]);
export const confirmModeSchema = z.enum(["chat", "terminal", "high-severity-terminal"]);

export const gateConfigSchema = z.object({
  enabled: z.boolean(),
  mode: gateModeSchema,
  businessScopes: z.array(z.string()),
  toolsMatcher: z.string(),
  decisionsFile: z.string(),
  confirmMode: confirmModeSchema,
  failClosed: z.boolean(),
});

export const orchestrationModeSchema = z.enum(["prescriptive"]);

export const orchestrationConfigSchema = z.object({
  enabled: z.boolean(),
  mode: orchestrationModeSchema,
  defaultWorkflow: z.enum(["coding"]),
  stepAwareGate: z.boolean(),
  requireReviewBeforeComplete: z.boolean(),
  runsFile: z.string(),
  eventsFile: z.string(),
});

export const harnessConfigSchema = z.object({
  agents: z.array(agentSchema).min(1),
  targets: z.object({
    claude: targetConfigSchema,
    cursor: targetConfigSchema,
    codex: targetConfigSchema,
    windsurf: targetConfigSchema,
    copilot: targetConfigSchema,
  }),
  rulesDir: z.string(),
  contextFile: z.string(),
  memoryFile: z.string(),
  archiveFile: z.string(),
  stateFile: z.string(),
  header: z.string(),
  maxLearningsPerFile: z.number().int().positive(),
  dedupeGlobal: z.boolean(),
  scan: scanConfigSchema,
  discover: discoverConfigSchema,
  srs: srsConfigSchema,
  gate: gateConfigSchema,
  orchestration: orchestrationConfigSchema,
});

export type HarnessConfig = z.infer<typeof harnessConfigSchema>;
export type AgentName = z.infer<typeof agentSchema>;
export type GateConfig = z.infer<typeof gateConfigSchema>;
export type GateMode = z.infer<typeof gateModeSchema>;
export type ConfirmMode = z.infer<typeof confirmModeSchema>;
export type OrchestrationConfig = z.infer<typeof orchestrationConfigSchema>;

/** Gate defaults — public contract for v0.2 consumers (S1/S2/S3). */
export function defaultGateConfig(): GateConfig {
  return {
    enabled: true,
    mode: "sensitive-only",
    businessScopes: ["src/**", "lib/**", "app/**", "docs/srs/**"],
    toolsMatcher: "Write|Edit|MultiEdit|NotebookEdit|Bash",
    decisionsFile: ".contextpilot/decisions/decisions.jsonl",
    confirmMode: "chat",
    failClosed: true,
  };
}

export function defaultOrchestrationConfig(): OrchestrationConfig {
  return {
    enabled: true,
    mode: "prescriptive",
    defaultWorkflow: "coding",
    stepAwareGate: true,
    requireReviewBeforeComplete: true,
    runsFile: ".contextpilot/orchestration/runs.jsonl",
    eventsFile: ".contextpilot/orchestration/events.jsonl",
  };
}

export function defaultConfig(agents: AgentName[] = ["claude", "cursor", "codex"]): HarnessConfig {
  return {
    agents,
    targets: {
      claude: { output: "CLAUDE.md" },
      cursor: { output: ".cursor/rules/" },
      codex: { output: "AGENTS.md" },
      windsurf: { output: ".windsurfrules" },
      copilot: { output: ".github/copilot-instructions.md" },
    },
    rulesDir: ".contextpilot/rules",
    contextFile: ".contextpilot/context/current.md",
    memoryFile: ".contextpilot/memory/learnings.jsonl",
    archiveFile: ".contextpilot/memory/archive.jsonl",
    stateFile: ".contextpilot/state.json",
    header: "<!-- Auto-generated by ContextPilot. Do not edit manually. -->",
    maxLearningsPerFile: 30,
    dedupeGlobal: true,
    scan: {
      include: ["docs/**", ".github/**", "*.md"],
      exclude: ["node_modules", "dist", "README.md", "CHANGELOG.md", "LICENSE.md"],
      maxDepth: 3,
    },
    discover: {
      paths: {},
      dedupeGlobal: true,
    },
    srs: {
      path: "docs/srs",
      skillPath: ".contextpilot/skills/fullstack-to-srs",
      moduleMap: {},
    },
    gate: defaultGateConfig(),
    orchestration: defaultOrchestrationConfig(),
  };
}
